### ISSUE TITLE
stm32mp1: DIGBYP bit in RCC_BDCR is incorrectly set to read-only

### ISSUE THREAD

**Issue by AmateurECE** [stm32-rs/stm32-rs#1010]
Hi there!

The DIGBYP bit in the RCC_BDCR register for the stm32mp15{3,7} platforms is incorrectly set to read-only in the SVD files, as you can see from the following snippet:

```
<field>
	<name>DIGBYP</name>
	<description>DIGBYP</description>
	<bitOffset>3</bitOffset>
	<bitWidth>1</bitWidth>
	<access>read-only</access>
</field>
```

The datasheet for the parts states that this field is read/write and what its use is for software (see below images). I only noticed because the STM32CubeMP1 HAL code [clears this bit when setting up](https://github.com/STMicroelectronics/STM32CubeMP1/blob/master/Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_rcc.c#L921) the RCC external low speed oscillator (LSE).

![image](https://github.com/user-attachments/assets/8c099dbc-7566-487e-879e-bf526db270a9)

![image](https://github.com/user-attachments/assets/387b110f-5036-4516-850a-00febfaa001a)

I took a quick look through the git commit history and the `extract.sh` script, but I didn't really see a precedent for making corrections to the SVD files. Do you prefer for these changes to be made directly to the SVD files themselves and committed, or would you prefer for them to be added as patches that get applied to the SVD files when `extract.sh` is run?

**Comment by burrbull** [comment]
> Do you prefer for these changes to be made directly to the SVD files themselves

No. No manual changes in SVD files, except updating original archive.

To patch file you need to use patching system.
