### ISSUE TITLE
HRTIM - Naming master timer vs normal timer

### ISSUE THREAD

**Issue by usbalbin** [stm32-rs/stm32-rs#1027]
@burrbull

All of [HRTIM_MASTER's registers](https://docs.rs/stm32g4-staging/0.18.0/stm32g4_staging/stm32g474/hrtim_master/index.html) are prefixed with an `m` while some of the [other timers registers](https://docs.rs/stm32g4-staging/0.18.0/stm32g4_staging/stm32g474/hrtim_tima/index.html) are prefixed with `tim`

Some examples 

| HRTIM_MASTER | HRTIM_TIMA |
|-------------------------|--------------------|
|    **m**cmp1r   | cmp1r             |
|    **m**dier       |**tim**dier    |

Would it make sense to strip those prefixes to make the naming more consistent?

**Comment by burrbull** [comment]
Yes. Makes sense. I'll look what can I do.

**Comment by burrbull** [comment]
Should we rename `MPER => PERR`, `MREP => REPR`?

**Comment by burrbull** [comment]
Try this branch: https://github.com/stm32-rs/stm32-rs/tree/hrtim-master

**Comment by usbalbin** [comment]
That is really nice!

I also noticed that the HRTIM_TIMERx's capture register 2 `cpt2r` seems to contain the bitfield `cpt1` in your branch. Would it make sense if both `cpt1r` and `cpt2r` just contained the bitfield `cpt`?

**Comment by burrbull** [comment]
> I also noticed that the HRTIM_TIMERx's capture register 2 `cpt2r` seems to contain the bitfield `cpt1` in your branch. Would it make sense if both `cpt1r` and `cpt2r` just contained the bitfield `cpt`?

Should be fixed in last commit.

**Comment by burrbull** [comment]
Open PR, pls.

**Comment by burrbull** [comment]
Check and open PR from https://github.com/stm32-rs/stm32-rs/tree/hrtim-common

**Comment by burrbull** [comment]
https://github.com/stm32-rs/stm32-rs/tree/hrtim-rstr

**Comment by usbalbin** [comment]
@burrbull would you mind creating a new release of [stm32g4-staging](https://crates.io/crates/stm32g4-staging) with the new hrtim changes?

**Comment by burrbull** [comment]
done
