### ISSUE TITLE
Adapt SVD patches from stm32f103xx

### ISSUE THREAD

**Issue by mvirkkunen** [stm32-rs/stm32-rs#104]
There are some valuable SVD patches in the stm32f103xx crate that could be adapted to the stm32f1 crate. Among other things they add enumerated values for many fields which currently only have a `bits()` method in stm32f1.

The patches are a plain patch file against the SVD XML files, so converting them to the format used in this project requires some work.

https://github.com/japaric/stm32f103xx/blob/ca6a494e497a2ab7428a81a60d4fd1035d906977/STM32F103xx.patch

**Comment by therealprof** [comment]
@mvirkkunen I don't actually mind the bit(s) stuff, it's actually easier to see what is going on than when hiding them behind made up names by looking at the datasheet.

Of course the USB stuff needs fixing, that's just completely bogus.

**Comment by burrbull** [comment]
This issue can be closed.

**Comment by adamgreig** [comment]
:+1:, thanks for all your hard work on the F1 patches!
