### ISSUE TITLE
Update to svd2rust 0.14

### ISSUE THREAD

**Issue by MabezDev** [stm32-rs/stm32-rs#105]
Hey,

I know svd2rust 0.14 has only been out for a few days but it would be great if we could get a new version out so that we can try out [cortex-rt-rtfm-v4](https://github.com/japaric/cortex-m-rtfm).

Cheers

**Comment by adamgreig** [comment]
Yep, I hope to have stm32-rs 0.5.0 released in a day or two using svd2rust 0.14. Watch this space!

**Comment by MabezDev** [comment]
Sweet! Look forward to it.

**Comment by adamgreig** [comment]
Done in #108
