### ISSUE TITLE
IOPDEN in ahbenr is missing for STM32F0x0

### ISSUE THREAD

**Issue by david-sawatzke** [stm32-rs/stm32-rs#106]
The iopden bit in ahbenr is missing for stm32f0x0 devices. The stm32f030r8 & stm32f030rc both have this port and it's documented in the reference manual.

EDIT:
The usart6en bit in apb2enr is missing as well

**Comment by adamgreig** [comment]
Thanks for the bug report! I believe both issues were fixed in #99 which has been merged but not yet released; I hope to release version 0.5 in the next couple of days with svd2rust 0.14.0 support which will also include those changes.
