### ISSUE TITLE
stm32f0x0 TIM3 ranges incorrect

### ISSUE THREAD

**Issue by x37v** [stm32-rs/stm32-rs#132]
TIM3 is a 16 bit timer for STM32f0x0, but the patching is done based on a 32bit timer so the ranges are 16 bits too wide.
The SVD indicates that there are `_H`, high values, for these registers but the description indicates that they are only for TIM2, which these devices don't have (I don't think).

**Comment by adamgreig** [comment]
I believe this is essentially fixed now (by afd9b28 / #241).
