### ISSUE TITLE
Allow replacing a second identical device by a derivedFrom

### ISSUE THREAD

**Issue by aurelj** [stm32-rs/stm32-rs#145]
For example, in stm32f7x2, there are both a `USART1` and `USART3` that are fully defined. Both of them are entirely identical except for one field that is misnamed in `USART3`, and fixed by `devices/common_patches/rename_USART_CR2_DATAINV_field.yaml` to make them perfectly identical.

Still we end up with 2 totally independent implementations with their own `RegisterBlock`. It would be great if we could just patch `USART3` simply as `derivedFrom="USART1"`.

**Comment by adamgreig** [comment]
Closed by #98
