### ISSUE TITLE
stm32f4xx TIM3/4 ARR should be 16 bits, is 32

### ISSUE THREAD

**Issue by cbiffle** [stm32-rs/stm32-rs#147]
Per the STM32F4 family reference manual, section 18.2, the timer sizes for TIM2-TIM5 are

> 16-bit (TIM3 and TIM4) or 32-bit (TIM2 and TIM5)

But `stm32::stm32f407::tim3::arr::_ARRW` takes a `u32`. It should take a `u16`.

**Comment by cbiffle** [comment]
This also affects the other timer-sized registers on TIM3/TIM4: CCR1, CCR2, CNT, etc.

**Comment by jessebraham** [comment]
This seems to be related to #132 as well
