### ISSUE TITLE
Support stm32-compatibles?

### ISSUE THREAD

**Issue by ehntoo** [stm32-rs/stm32-rs#152]
There are an [increasing](https://lcsc.com/search?q=32f103c8t6) [number](https://www.cnx-software.com/2019/02/10/cs32-mcu-stm32-clone-bluepill-board/) of mostly-stm32 compatible microcontrollers coming out, with varying levels of "mostly" in their compatibility.

I'm about to start fiddling with the "MindMotion" and "Betterlife" F103-alikes due to their low cost, 5v-tolerant operating voltage, and the fact that unlike the native ST parts, the CAN and USB peripherals don't share an SRAM region for message buffering.

Should this project also be home to support for these microcontrollers, or would it be better to have them in their own crate/project? I have only just started poking around the SVDs for these parts, and don't yet have a good feel for their relative levels of brokenness compared to the ST files.

**Comment by adamgreig** [comment]
I think probably best to keep those devices in their own crates, at least for the time being. They could potentially copy some of the work from here. I'd hope the more-compatible devices could just use the crates from here directly (the SRAM region addresses are not part of these crates anyway, for example), but I'm not sure how the compatibility plays out.

There is also some concern that the licence for the ST-provided data files permits their use only on ST products and not clones.
