### ISSUE TITLE
No way to access ccmr1_input

### ISSUE THREAD

**Issue by tdaede** [stm32-rs/stm32-rs#154]
The type is defined, but the RegisterBlock only defines ccmr1_output and there is no obvious way to convert between the two.

**Comment by tdaede** [comment]
On stm32f401 to be specific, but I don't see a way to access it on other CPUs.

**Comment by adamgreig** [comment]
This is really an svd2rust issue (https://github.com/rust-embedded/svd2rust/issues/16) which we can't solve here.

You _can_ use the `.bits()` method on `CCMR1_OUTPUT` to directly read/write the equivalent `CCMR1_Input` fields though it's inelegant.
