### ISSUE TITLE
Where is SxPAR gone?

### ISSUE THREAD

**Issue by pferreir** [stm32-rs/stm32-rs#213]
DMA `RegisterBlock`s used to have and `.s0par` field. That doesn't seem to be the case anymore.
From what I see, all other `Sx` registers have been moved to `.st[x]`, but that doesn't seem to be the case for `SxPAR`.

**Comment by adamgreig** [comment]
Looks like PAR is missing from https://github.com/stm32-rs/stm32-rs/blob/master/devices/common_patches/dma/dma_v2.yaml

**Comment by adamgreig** [comment]
Thanks for reporting! Version 0.7.1 contains the fix for this.

**Comment by pferreir** [comment]
That was fast, thanks!
