### ISSUE TITLE
f103 BKP registers incorrect offset

### ISSUE THREAD

**Issue by jrobsonchase** [stm32-rs/stm32-rs#260]
There appears to be a discrepancy between the stm32f103 svd and the reference regarding the locations of the backup domain regsiters. The SVD has the backup domain beginning at 0x40006C00 and the first register (DR1) at offset 0x00 from the base. The reference, however, has a 32-bit "reserved" region at the start of the register block with DR1 being at offset 0x04.

I haven't checked the svd/reference for any other chip, but it seems likely that they could have the same error. Probably worth some more investigation.

**Comment by burrbull** [comment]
https://github.com/stm32-rs/stm32-rs/pull/256

**Comment by adamgreig** [comment]
Closed by #256.
