### ISSUE TITLE
STM32H755

### ISSUE THREAD

**Issue by jheyens** [stm32-rs/stm32-rs#282]
Hi,

I recently got an STM32/NUCLEO-H755ZI-Q and I found the [H7 series support crate](https://crates.io/crates/stm32h7). I created a small sample project using that crate and would like to contribute here to add support for this device. 
The device seems to be quite similar to the H7x3, such that I don't expect to be a lot of manual labour required. 
However, the 755 devices are dual-CPU and with this crate, I was obviously only able to launch code on the main CortexM7 CPU. 

Since the device is support by STM with the same SVD file used by the H7x3 devices, I am not quite sure what is needed to add other devices here. 
I would appreciate a few hints on what is going to be needed here.
So, how can I help?

Jens

**Comment by newAM** [comment]
Since this issue was opened a HAL for the H7 has been created: https://github.com/stm32-rs/stm32h7xx-hal

I am going to close this issue, if this doesn't resolve it feel free to re-open!
