### ISSUE TITLE
Wrong SADD field configuration in I2C1.CR2 register for stm32f303

### ISSUE THREAD

**Issue by zhenkyle** [stm32-rs/stm32-rs#334]
In https://docs.rs/stm32f3/0.9.0/src/stm32f3/stm32f303/i2c1/cr2.rs.html#851, we can see
```rust
    #[doc = "Bits 0:9 - Slave address bit 9:8 (master mode)"]
    #[inline(always)]
    pub fn sadd(&mut self) -> SADD_W {
        SADD_W { w: self }
    }
```
It doesn't sounds right. In the stm32f303's reference manual [RM0316](http://www.st.com/resource/en/reference_manual/dm00043574.pdf), page 873, we can see there are two filed named SADD and one field named SADD0:
```
Bits 9:8 SADD[9:8]: Slave address bit 9:8 (master mode)
Bits 7:1 SADD[7:1]: Slave address bit 7:1 (master mode)
Bit 0 SADD0: Slave address bit 0 (master mode)
```
So, at least, the SADD field in our I2C1.CR2 register is not just used for bit 9:8. In fact, it is better to split these three SADD fields, like it has been done in the [stm32f30x crate](https://github.com/japaric/stm32f30x/blob/master/src/i2c1/cr2/mod.rs#L767):
```rust
    #[doc = "Bits 8:9 - Slave address bit 9:8 (master mode)"]
    #[inline]
    pub fn sadd8(&mut self) -> _SADD8W {
        _SADD8W { w: self }
    }
    #[doc = "Bits 1:7 - Slave address bit 7:1 (master mode)"]
    #[inline]
    pub fn sadd1(&mut self) -> _SADD1W {
        _SADD1W { w: self }
    }
    #[doc = "Bit 0 - Slave address bit 0 (master mode)"]
    #[inline]
    pub fn sadd0(&mut self) -> _SADD0W {
        _SADD0W { w: self }
    }
```

So when using 7-bit addressing mode, we can now using SADD1 for 7-bit slave address directly, without any binary shift operation.

**Comment by adamgreig** [comment]
[What we have now](https://stm32.agg.io/rs/STM32F303.html#I2C1:CR2) matches the reference manual's diagram:

![image](https://user-images.githubusercontent.com/47219/74377888-bef39600-4ddc-11ea-87d1-79ef9d65f312.png)

I think of it as one `SADD` field which is interpreted differently depending on 7bit/10bit mode.

While splitting it into three fields might make 7-bit addressing slightly easier (though the shift-by-one should be essentially a no-op and is a common requirement for i2c addresses anyway), it would make using 10 bit addresses really hard - you'd have to split it into three separate integers and write them to three separate fields. We can't have overlapping fields, so could not have e.g. `SADD` and also `SADD1`.

So, I think this is best as it already is.
