### ISSUE TITLE
STM32F107 Ethernet DMA bus mode register (`DMABMR`) missing Rx Tx priority ratio (`pm`) field.

### ISSUE THREAD

**Issue by mitchmindtree** [stm32-rs/stm32-rs#419]
I don't quite have the time to submit a patch for this at the moment so I thought I'd open an issue in the meantime.

The field is described in section 29.8.4 "DMA register description" of the STM32F1 reference manual:

> **PM**: Rx Tx priority ratio
> RxDMA requests are given priority over TxDMA requests in the following ratio:
> 00: 1:1
> 01: 2:1
> 10: 3:1
> 11: 4:1
> This is valid only when the DA bit is cleared.

**Comment by datdenkikniet** [comment]
This was fixed in #380

**Comment by mitchmindtree** [comment]
Not following this at the moment, but happy to close if addresed.
