### ISSUE TITLE
STM32L4x1 ADC common registers missing

### ISSUE THREAD

**Issue by ceigel** [stm32-rs/stm32-rs#452]
The following registers are missing for STM32L4x1: ADC_CCR, ADC_CSR, ADC_CDR. They are noted in the reference manual in section 16.7 (ADC Common Registers).

**Comment by korken89** [comment]
Hi, I just came to the same issue when trying to implement ADC for the L4 HAL.

**Comment by korken89** [comment]
@adamgreig This can be closed by my recent PRs

**Comment by adamgreig** [comment]
Thanks! Closed by #463 #465 #484.
