### ISSUE TITLE
STM32F0 I2C TXE register is marked read-only in SVD, but may be written to

### ISSUE THREAD

**Issue by barafael** [stm32-rs/stm32-rs#457]
The datasheet RM0091 page 682 says "This bit can be written to ‘1’ by software in order to flush the transmit data register I2C_TXDR". Because of the read-only definition in the SVD file (stm32f0x2.svd line 3077), it is not writable using the PAC.
I am not sure if this is wrong in the svd, or if this is just a very uncommon operation warranting an unsafe block and direct register manipulation.

**Comment by barafael** [comment]
To clarify, I think it is actually necessary to set that bit during I2C configuration. 

See here: https://github.com/barafael/stm32f0-rtic-smbus-slave/blob/main/src/main.rs#L190

Without setting that bit, somehow the TXDR messes up resulting in a wrong transmission.

**Comment by wallacejohn** [comment]
This issue may be confusing the TXE field in the SPI SR register (stm32f0x2.svd line 3077 mentioned above) with the TXE field in the I2C ISR register (stm32f0x2.svd line 4460). The SPI TXE field is read-only as described above and also matches the SPI chapter in RM0091. The I2C TXE field is read-write in the SVD and PAC and also matches the I2C chapter in RM0091.
