### ISSUE TITLE
STM32F302, USART3EN missing from APB2EN

### ISSUE THREAD

**Issue by korken89** [stm32-rs/stm32-rs#52]
As the title states, bit 18 in `APB2EN` should be `USART3EN`, however it is missing.

**Comment by bergus** [comment]
Related to #34?

**Comment by korken89** [comment]
Could be, but for a different line of MCUs.

**Comment by aurelj** [comment]
This is fixed now, USART3EN was added for STM32F302, and it is actually part of APB1ENR, not APB2ENR.

**Comment by adamgreig** [comment]
:+1:
