### ISSUE TITLE
Intellisense/autocomplete with rust-analyzer fails to deduce type of register read/modify/write callback

### ISSUE THREAD

**Issue by timblakely** [stm32-rs/stm32-rs#527]
Heya!

Loving the project so far (came from C++ and STM's, erm, underwhelming LL libs ;). 

With `rust-analyzer` and VSCode, I'm seeing a failure to deduce the callback parameter types from individual register `.(read|modify|write)(| | ...)` functions:

![image](https://user-images.githubusercontent.com/11380482/112712209-265a9100-8e8b-11eb-95b9-1a8871eab8de.png)

Compiles fine though using nightly. Any ideas on why the deduction fails?

**Comment by timblakely** [comment]
Apologies for the noise; looks like an update to the rust-analyzer plugin seems to now be deducing the types just fine.

![image](https://user-images.githubusercontent.com/11380482/112736761-66b12200-8f12-11eb-9aaa-81218625f616.png)

**Comment by adamgreig** [comment]
Glad to hear it!
