### ISSUE TITLE
STM32L4x6 LCD_RAM_COMx registers too small in SVD

### ISSUE THREAD

**Issue by AndreasKarg** [stm32-rs/stm32-rs#550]
The LCD_RAM_COMx registers are actually 8 bytes each.
In the PAC as well as the underlying SVD, they are declared as 4 bytes/32 bit, so the generated code ends up with undersized registers + 4 bytes padding after each.

I have raised this with ST, so hopefully they'll fix it at their end.

I'm happy to try my hand at PR'ing a patch here if that helps...

**Comment by AndreasKarg** [comment]
Fix PR'ed in #552

**Comment by adamgreig** [comment]
Closed by #552, thank you for reporting and fixing!
