### ISSUE TITLE
Patch release (0.13.1) for stm32f3

### ISSUE THREAD

**Issue by sirhcel** [stm32-rs/stm32-rs#560]
I started https://github.com/stm32-rs/stm32-rs/pull/558 to get the [_Discovery_ book UART example](https://github.com/rust-embedded/discovery/pull/267#issuecomment-822826949) safe again. The hanges have landed here and I could successfully test this with the [nightly `stm32f3` crate](https://github.com/stm32-rs/stm32-rs-nightlies/commit/c6084a3a2dede4dcaec861540dfd2356e56c7203).

To get this fix into the _Discovery_ examples, I would like to ask all the crate maintainers for an update. From my point of view, this is the crate to start with. Could you please make a patch/maintainance release for the `stm32f3` crate to get this started?

**Comment by adamgreig** [comment]
Thanks for the prompt, I've published stm32f3 0.13.1 with that fix.
