### ISSUE TITLE
STM32L4x3 PAC missing USB_BCDR register

### ISSUE THREAD

**Issue by David-OConnor** [stm32-rs/stm32-rs#563]
(Battery charging detector reg) Note: This is not present on some USB FS peripherals like on F3, which are otherwise the same. Offset 0x58.

Note that the [stm32-usbd PAC](https://github.com/stm32-rs/stm32-usbd/blob/master/src/pac/usb.rs) does include it.

**Comment by adamgreig** [comment]
Closed by #580
