### ISSUE TITLE
STM32L4x3 USB points to wrong addr

### ISSUE THREAD

**Issue by David-OConnor** [stm32-rs/stm32-rs#565]
https://github.com/stm32-rs/stm32-rs-nightlies/blob/master/stm32l4/src/stm32l4x3/mod.rs#L1347

Should be 0x4000_6800. The current one is the *USB SRAM* address. 

L4x2 PAC is correct. L4x1 PAC doesn't have USB. L4x6 PAC uses OTG. L4x5 PAC also has this error, but if I understand correctly, shouldn't even have this periph since it uses the OTG periph.

To fix, could copy + paste L4x2 USB module. Should be the same.

**Comment by adamgreig** [comment]
Closed by #580
