### ISSUE TITLE
WBx5 tim16 CR1 wrong fields

### ISSUE THREAD

**Issue by David-OConnor** [stm32-rs/stm32-rs#575]
Tim16 CR1 fields are wrong, as are TIM16 and TIM17 DIER. All 3 of these are showing the same fields.

[tim16 cr1 fields](https://docs.rs/stm32wb/0.13.0/stm32wb/stm32wb55/tim16/cr1/index.html)

(And the correct TIM17, which this should be the same as)
[tim17 cr1 fields](https://docs.rs/stm32wb/0.13.0/stm32wb/stm32wb55/tim17/cr1/index.html)

Incorrect DIER fields: https://docs.rs/stm32wb/0.13.0/stm32wb/stm32wb55/tim16/dier/index.html
Correct DIER fields (TIM1): https://docs.rs/stm32wb/0.13.0/stm32wb/stm32wb55/tim1/dier/index.html

**Comment by adamgreig** [comment]
Closed by #580
