### ISSUE TITLE
stm32wb vs stm32l4 EXTI10_15 vs EXTI15_10

### ISSUE THREAD

**Issue by karlp** [stm32-rs/stm32-rs#616]
I don't know the most correct path forwards to get this resolved, but the STM32WB and L4 disagree over the naming of one of the EXTI interrupts.  As the WB is an L4 with a radio, it would be nice if this was more unified...

L4: Uses EXTI15_10
https://github.com/stm32-rs/stm32-rs-nightlies/blob/master/stm32l4/src/stm32l4x6/mod.rs#L318

WB: Uses EXTI10_15
https://github.com/stm32-rs/stm32-rs-nightlies/blob/master/stm32wb/src/stm32wb55/mod.rs#L267

**Comment by adamgreig** [comment]
It looks like the difference is in the ST-provided SVDs. The L4 reference manual calls it `EXTI15_10`, the WB reference manual calls it `EXTI[15:10]`. It looks like the C headers use `EXTI15_10` in both, and all the other STM32s call it `EXTI15_10` too; the WB55 is the only one in stm32-rs that uses `EXTI10_15`.

At least it's pretty clear which way it should go! The fix will be adding an entry to `devices/stm32wb55.yaml` to rename the interrupt. Something like (untested):

```yaml
EXTI:
    _modify:
        _interrupts:
            EXTI10_15:
                name: EXTI15_10
```
