### ISSUE TITLE
H7 SAI xCR Master clock error

### ISSUE THREAD

**Issue by David-OConnor** [stm32-rs/stm32-rs#618]
It looks like the variant used for WB is correct, but it's also the same on H7. Specifically: The H7 PAC (probably SVD) has ACR and BCR bit 19 as NODIV, and 27 as MCKEN. This is correct per WB RM. H7 RM states 27 is not used, and 19 is NOMCK.

Of note, the SAI periph seems similar or identical other than this, and NODIV and MCKEN both relate to generating a master clock.

In the meanwhile, without forking, you can pretend the H7 NODIV field is NOMCK.

**Comment by adamgreig** [comment]
It looks like all our STM32H7 SVDs have the exact same SAI registers and fields, and they're all pretty badly wrong compared to the RMs. All the B registers are missing, and the A registers are all offset by 4, so CR1 aliases GCR.

In terms of this specific problem though: many of the H7 RMs do have 19 as NODIV and 27 as MCKEN, I think only the 743/753 (RM0433) has NOMCK nistead. As far as I can tell this is a genuine difference, not an RM error, and the other H7 and WB probably use a newer version of the SAI peripheral.

**Comment by adamgreig** [comment]
This was renamed in #347 to deliberately go against the RM in preference of consistency with the other devices. That said, looking at the RMs I'm not clear if NODIV and NOMCK are the same:

![image](https://user-images.githubusercontent.com/47219/135735524-1f7ef624-a853-4430-8ba6-cb99060314d8.png)

![image](https://user-images.githubusercontent.com/47219/135735528-a161d749-ee00-4b4f-817c-af17a798ee4c.png)

![image](https://user-images.githubusercontent.com/47219/135735531-01935569-d3ae-455d-8649-a6733ff42a2a.png)

@richardeoin, any thoughts?

**Comment by David-OConnor** [comment]
Good find, and my reaction was that we cannot assume it's the same.

**Comment by richardeoin** [comment]
What's happening here is that [AB]CR bit 19 has two related functions, and each RM picks a different one from those two functions to use in the bit description. In fact, the bit has both functions on all H7 parts.

## RM0433

||Function 1 | Function 2
|---|---|---
| bit 19 NOMCK = 0 | master clock enable = 1 | frequency ratio between FS and MCLK is fixed to 256 or 512 (RM0433 rev 7 p2266 bottom paragraph) |
| bit 19 NOMCK = 1 | master clock enable = 0 | frequency ratio depends on FRL |

## RM0399 RM0455 etc

||Function 1 | Function 2
|---|---|---
| bit 19 NODIV = 0 | master clock enable = 1 | frequency ratio between FS and MCLK is fixed to 256 or 512 (RM0399 rev 3 p2422 first bullet point) |
| bit 19 NODIV = 1 | master clock enable = `MCKEN` | frequency ratio depends on FRL (RM0399 rev 3 p2422 second bullet point) |

The "Audio block clock generator overview" figures in each RM show how NOMCK/NODIV is used twice.

**Comment by richardeoin** [comment]
Since this is terribly confusing, I'm thinking the best way forward is to match the RM bit naming exactly (so different names for bit 19) but write a better bit description that applies both to NOMCK, NODIV

**Comment by David-OConnor** [comment]
How does bit 27 play into this? It's missing from the H7 RM entirely.

**Comment by adamgreig** [comment]
There's four H7 reference manuals: RM0399, RM0433, RM0455, and RM0468, covering different H7s: bit 27 MCKEN is only missing from RM0433, but it's present in the others. When it's missing (in RM0433 devices i.e. 742, 743/53, 750), bit 19 (NOMCK) disables MCK entirely if set, and enables it if cleared, whereas with the other H7s, bit 19 (NODIV) delegates control to bit 27 MCKEN if set, which can then enable or disable it, but if NODIV is clear, MCK is always enabled.

I'm just summarising @richardeoin's comment above: basically, bit 19 does the same thing on all H7s, even though the name changes, because some newer devices also add bit 27 MCKEN, which works together with bit 19 to potentially disable MCK.
