### ISSUE TITLE
STM32 WL GPIO and EXTI missing fields

### ISSUE THREAD

**Issue by David-OConnor** [stm32-rs/stm32-rs#630]
- RTSR / FTSR fields: https://docs.rs/stm32wl/0.13.0/stm32wl/stm32wle5/exti/rtsr1/index.html
- GPIO port C IDR fields between 6 and 13: https://docs.rs/stm32wl/0.13.0/stm32wl/stm32wle5/gpioc/idr/index.html

**Comment by newAM** [comment]
* RTSR and FTSR fields were added in 0.14
* GPIOC IDR 7-23 do not exist because there are no physical pins on port C in that range.

Can this issues be closed?

**Comment by David-OConnor** [comment]
Yep!
