### ISSUE TITLE
Where is stm32f1::stm32f103::rcc::cr::PLLRDY_R?

### ISSUE THREAD

**Issue by serg-maks** [stm32-rs/stm32-rs#739]
Where is stm32f1::stm32f103::rcc::cr::PLLRDY_R?
And "pub type PLLON_A = HSION_A" in stm32f1::stm32f103::rcc::cr. Mayby it's wrong?
If i try set on the pllon register, my microcontroller freeze on "while rcc.cr.read().pllrdy().is_not_ready();".

**Comment by burrbull** [comment]
![изображение](https://user-images.githubusercontent.com/3072754/169651237-bebb52f9-080e-4cbe-be4f-29d4cc88085e.png)
