### ISSUE TITLE
0.15 SAI FSDEF removed

### ISSUE THREAD

**Issue by David-OConnor** [stm32-rs/stm32-rs#749]
https://docs.rs/stm32h7/latest/stm32h7/stm32h743/index.html?search=fsdef

From cha and chb. Worked previously. Affects H7 and L4 at least.

**Comment by burrbull** [comment]
According to RM `FSDEF` is read-only.

**Comment by adamgreig** [comment]
This is from #691 which changed FSDEF from read-write to read-only, but FSDEF is still present in FRCR ([here](https://docs.rs/stm32h7/latest/stm32h7/stm32h743/sai4/ch/frcr/struct.R.html#method.fsdef)). However while the RM does say FSDEF is read-only, the description of the bit says "set and cleared by software", so it looks like it does need to be read-write.
