### ISSUE TITLE
No QUADSPI for L4R5?

### ISSUE THREAD

**Issue by mattcarp12** [stm32-rs/stm32-rs#750]
Looks like QUADSPI is getting generated for all the L4 family chips except for L4R5.

Any tips on how I can investigate this?

**Comment by adamgreig** [comment]
Does the L4R5 have QUADSPI? I think all the L4+ chips in RM0432 have OCTOSPI instead of QUADSPI, which is being generated.

**Comment by mattcarp12** [comment]
Ah sorry for the misunderstanding. Thank you!
