### ISSUE TITLE
No access to cortex_m::interrupt::disable()?

### ISSUE THREAD

**Issue by erazor-de** [stm32-rs/stm32-rs#787]
I'm using
rustc 1.65.0 (897e37553 2022-11-02)
stm32f1 = { version = "0.15.1", features = ["stm32f103", "rt"] }

using stm32f1::stsm32f103 I can't find a way to access the cortex_m::interrupt::disable() and enable() functions. The only way I found is to depend on cortex_m myself. Am I doing something wrong or is this intentional?

The stm32f103/mod.rs has the lines
```
pub use self::Interrupt as interrupt;
pub use cortex_m_rt::interrupt;
```
Which means I can't even use the #[interrupt] attribute this crate should reexport (like cortex_m_rt documentation states).

**Comment by adamgreig** [comment]
The PACs don't expose `cortex_m::interrupt`; you should just use that by depending on the `cortex-m` crate yourself directly. These days you might look at using the `critical-section` crate, which provides a cross-platform way to enter/exit critical sections that's good for generic drivers, but if you're always targetting an stm32f103 then `cortex_m::interrupt::free()` is probably good enough (if you enable the `critical-section-single-core` feature on `cortex-m`, that's what it will use).

The `interrupt` exports you listed from the PAC are from `cortex-m-rt` (not `cortex-m`) and are the attribute macro for defining interrupt handlers, which must be re-exported from the PAC in a way that aliases the list of interrupts (`self::Interrupt`) for that macro to work (see [here](https://docs.rs/cortex-m-rt/latest/cortex_m_rt/attr.interrupt.html) for some more details). They're used like:

```rust
use stm32f1::stm32f103::{self, interrupt};

#[cortex_m_rt::entry]
fn main() -> ! {
    let dp = stm32f103::Peripherals::take().unwrap();
    cortex_m::interrupt::free(|cs| {
        // ...
    });
    loop {}
}

#[interrupt]
fn TIM2() {
    // ...
}
```
