### ISSUE TITLE
stm32f3xx_hal vs stm32f3 

### ISSUE THREAD

**Issue by tomasApo** [stm32-rs/stm32-rs#794]
## How do these two crates compare?

- These seem to achieve similar outcomes but I've had far more success with the stm32f3xx_hal.
- Currently working on a university project with the hal crate, should I be converting to the stm32f3 crate as _it centralises the community of STM32's?_  
- One is a 'hal' and the other an API? 
![image](https://user-images.githubusercontent.com/75183079/209870676-b9e8d9bf-d8d0-4885-b9e3-d4e6691fefff.png)

**Comment by tomasApo** [comment]
https://crates.io/crates/stm32f3xx-hal vs https://crates.io/crates/stm32f3

**Comment by burrbull** [comment]
stm32f3 is register level like cmsis
stm32f3xx-hal depends on stm32f3
